#!/usr/bin/env node

var act = process.argv [2];
var num = +process.argv [3];
var num2 = +process.argv [4];

if (act === "add") {
	console.log(num + num2);
}

else if (act === "sub") {
	console.log(num - num2);
}

else if (act === "mult") {
	console.log(num * num2);
}

else if (act === "div") {
	console.log(num / num2);
}
